apiVersion: v1
kind: Service
metadata:
  name: redis-test
  namespace: default
  labels:
    service: redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - name: input
    nodePort: 31666
    port: 6379
    protocol: TCP
    targetPort: 6379